get_post/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trail/',views.trial,name="trial"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def trial(request):
    return HttpResponse("<h1>Project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"myapp/home.html")

def profile(request):
    name="Rana"
    return render(request,"myapp/profile.html",{'name':name})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})

def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1> Thanks for submission Mr.{}</h1>".format(name)) 
    return render(request,"post_demo.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE Page</title>
    {% endblock %}
    <link rel="stylesheet" href="{%static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-grid-min.css' %}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>




</head>
<body>
  {% include "partials/_topbar.html" %}
  {% include "partials/_navbar.html" %}
  
  
    {% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to base page</h1>
            <img src="{% static 'images/wallpaper.png' %}" alt='no image found' height='50' width='100'>
        </div>
      </div>
    {% endblock %}


    {% include "partials/_footer.html" %}

</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GET DEMO</title>
</head>
<body>
    <form method="GET">

        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
    <h1>{{name}}</h1>


</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Home page</h1>
        </div>
      </div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile page</h1>
        </div>
      </div>
{% endblock %}

templates/partials/_footer.html
<!-- footer -->
<div class="alert alert-primary" role="alert">
    <center>Footer</center> 
  </div>

templates/partials/_navbar.html
<!-- navbar -->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
        </li>
        
      </ul>
</div>

templates/partials/_topbar.html
<!-- topbar -->
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center> 
 </div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POST DEMO</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
    


</body>
</html>